model = "gpt-5.1-codex"
model_reasoning_effort = "medium"

[general]
log_level = "info"

[projects."~/Documents/zeda_video"]
trust_level = "trusted"

[projects."~/Documents/vercel-codex-autofix"]
trust_level = "trusted"

[features] web_search_request = true

[mcp_servers.next-devtools]
command = "npx"
args = ["-y","next-devtools-mcp@0.3.9"]

[mcp_servers.context7]
command = "npx"
args = ["-y", "@upstash/context7-mcp"]